freq = [30, 90, 180]
freq_dict = {30: 'M',
             90: 'Q',
             180: '2Q'}
criteria_dict = {'mean': ['10%', '20%', '30%', '40%'],
                 'MDD': ['90%', '80%', '70%'],
                 'DD_pct': [30, 20, 10],
                 'kelly': [0, 0.1, 0.15],
                 'winrate': [30, 40, 50],
                 'hazard': [0.5, 1, 2],
                 'volatility': ['90%', '80%', '70%'],
                 'avg_wl': [1, 2],
                 'pf_factor': [1, 1.5],
                 'last': [1]}
criteria_operator = {'mean': '>',
                     'MDD': '<',
                     'DD_pct': '<',
                     'kelly': '>',
                     'winrate': '>',
                     'hazard': '>',
                     'volatility': '<',
                     'avg_wl': '>',
                     'pf_factor': '>',
                     'sharpe': '>',
                     'last': '&',
                     "log_ret": '>',
                     "return": '>',
                     "abs_r": '>',
                     "range": '>',
                     "ATR": '>'}
longterm = ['Employment, Hours, and Earnings from the Current Employment Statistics survey (National)',
            'Labor Force Statistics from the Current Population Survey',
            'U.S. Crude Oil Inventories']
econ_criteria_dict = {"log_ret": [0, 0.01, 0.05],
                      "return": [0.9, 1, 1.1],
                      "abs_r": [0.1, 0.3, 0.5],
                      "range": ['30%', '50%', '70%'],
                      "ATR": ['30%', '50%', '70%']}
